version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-node:
    executor: node/default
    resource_class: large
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build project
          command: npm install && npm run build
workflows:
  build_and_test:
    jobs:
      - build-node