name: Github Action (Branch Develop)

on:
  push:
    branches:
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord - Build Started
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\":rocket: Build started :rocket: for PR #${{ github.event.pull_request.number }} by ${{ github.actor }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tick-task:pr-${{ github.event.pull_request.number }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tick-task:pr-${{ github.event.pull_request.number }}

      - name: Notify Discord - Build Success
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\":white_check_mark: Build succeeded ✅ for PR #${{ github.event.pull_request.number }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord - Build Failed
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\":x: Build failed ❌ for PR #${{ github.event.pull_request.number }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
  
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Notify Discord - Deploy Started
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\":rocket: Deploy :rocket: started on \`dev\`\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
        
      - name: Wait and Check Health
        run: |
          echo "Waiting for app to start..."
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.HTTP_HEALTHCHEZ }}")

            if [ "$STATUS" -eq 200 ]; then
              echo "✅ Health check passed"
              exit 0
            else
              echo "❌ Health check failed (HTTP $STATUS), retrying in 10s..."
              sleep 10
            fi
            done

          echo "🚨 App failed health check after timeout"
          exit 1

      - name: Notify Discord - Deploy Success
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\":white_check_mark: Render deploy success!\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord - Deploy Failed
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\":\":x: Render deploy failed!\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
